import {
  createGemPainter,
  paintBarrel,
  paintBoulderCracked,
  paintBoulderRound,
  paintBrickIndustrial,
  paintChestClosed,
  paintChestOpen,
  paintDoorClosed,
  paintDoorOpen,
  paintCircuit,
  paintCrystal,
  paintCrate,
  paintDirtClassic,
  paintDirtGrassTop,
  paintDirtMossy,
  paintDirtPebble,
  paintExitClosed,
  paintExitOpen,
  paintGemDiamond,
  paintGrassBright,
  paintGrassSparse,
  paintIce,
  paintKeyTile,
  paintLava,
  paintLadderWood,
  paintMetalGrate,
  paintMetalPanel,
  paintMetalRiveted,
  paintMushroomBlue,
  paintMushroomRed,
  paintPatternChecker,
  paintPatternDiamond,
  paintPatternWaves,
  paintSignpost,
  paintSandCool,
  paintSandWarm,
  paintSteelPlate,
  paintStoneBlock,
  paintStoneGranite,
  paintStoneRuins,
  paintWaterDeep,
  paintWaterFoam,
  paintWaterShallow,
  paintWoodPlanks,
  paintTreeOak,
  paintTreePalm,
  paintTreePine,
} from './painters.js';

export const standardTileDefinitions = [
  { id: 'dirt/classic', label: 'Classic Dirt', category: 'Dirt', painter: paintDirtClassic('standard/dirt-classic') },
  { id: 'dirt/pebble', label: 'Pebbled Dirt', category: 'Dirt', painter: paintDirtPebble('standard/dirt-pebble') },
  { id: 'dirt/mossy', label: 'Mossy Dirt', category: 'Dirt', painter: paintDirtMossy('standard/dirt-mossy') },
  { id: 'dirt/grass-top', label: 'Dirt with Grass', category: 'Dirt', painter: paintDirtGrassTop('standard/dirt-grass') },
  { id: 'grass/bright', label: 'Bright Grass', category: 'Grass', painter: paintGrassBright('standard/grass-bright') },
  { id: 'grass/sparse', label: 'Sparse Grass', category: 'Grass', painter: paintGrassSparse('standard/grass-sparse') },
  { id: 'stone/block', label: 'Stone Block', category: 'Stone', painter: paintStoneBlock('standard/stone-block') },
  { id: 'stone/granite', label: 'Granite Stone', category: 'Stone', painter: paintStoneGranite('standard/stone-granite') },
  { id: 'stone/ruins', label: 'Ruined Stone', category: 'Stone', painter: paintStoneRuins('standard/stone-ruins') },
  { id: 'stone/brick', label: 'Industrial Brick', category: 'Stone', painter: paintBrickIndustrial() },
  { id: 'metal/panel', label: 'Steel Panel', category: 'Metal', painter: paintMetalPanel('standard/metal-panel') },
  { id: 'metal/riveted', label: 'Riveted Steel', category: 'Metal', painter: paintMetalRiveted('standard/metal-riveted') },
  { id: 'metal/grate', label: 'Metal Grate', category: 'Metal', painter: paintMetalGrate('standard/metal-grate') },
  { id: 'metal/plate', label: 'Heavy Plate', category: 'Metal', painter: paintSteelPlate() },
  { id: 'wood/planks', label: 'Wood Planks', category: 'Wood', painter: paintWoodPlanks('standard/wood-planks') },
  { id: 'sand/warm', label: 'Warm Sand', category: 'Sand', painter: paintSandWarm('standard/sand-warm') },
  { id: 'sand/cool', label: 'Cool Sand', category: 'Sand', painter: paintSandCool('standard/sand-cool') },
  { id: 'water/shallow', label: 'Shallow Water', category: 'Water', painter: paintWaterShallow('standard/water-shallow') },
  { id: 'water/deep', label: 'Deep Water', category: 'Water', painter: paintWaterDeep('standard/water-deep') },
  { id: 'water/foam', label: 'Foamy Water', category: 'Water', painter: paintWaterFoam('standard/water-foam') },
  { id: 'lava/default', label: 'Molten Lava', category: 'Elemental', painter: paintLava('standard/lava') },
  { id: 'ice/default', label: 'Icy Floor', category: 'Elemental', painter: paintIce('standard/ice') },
  { id: 'pattern/checker', label: 'Checker Pattern', category: 'Pattern', painter: paintPatternChecker() },
  { id: 'pattern/diamond', label: 'Diamond Pattern', category: 'Pattern', painter: paintPatternDiamond() },
  { id: 'pattern/waves', label: 'Wave Pattern', category: 'Pattern', painter: paintPatternWaves() },
  { id: 'pattern/circuit', label: 'Circuit Board', category: 'Pattern', painter: paintCircuit('standard/circuit') },
  { id: 'crystal/purple', label: 'Purple Crystal', category: 'Special', painter: paintCrystal('standard/crystal') },
  { id: 'gem/emerald', label: 'Emerald Gem', category: 'Special', painter: createGemPainter({ hue: 140 }) },
  { id: 'gem/ruby', label: 'Ruby Gem', category: 'Special', painter: createGemPainter({ hue: 2 }) },
  { id: 'gem/diamond-blue', label: 'Blue Diamond', category: 'Special', painter: paintGemDiamond('standard/gem-diamond') },
  { id: 'boulder/round', label: 'Round Boulder', category: 'Special', painter: paintBoulderRound() },
  { id: 'boulder/cracked', label: 'Cracked Boulder', category: 'Special', painter: paintBoulderCracked('standard/boulder-cracked') },
  { id: 'key/golden', label: 'Golden Key', category: 'Special', painter: paintKeyTile() },
  { id: 'door/closed', label: 'Wooden Door', category: 'Special', painter: paintDoorClosed() },
  { id: 'door/open', label: 'Wooden Door (Open)', category: 'Special', painter: paintDoorOpen() },
  { id: 'exit/closed', label: 'Exit Gate', category: 'Special', painter: paintExitClosed() },
  { id: 'exit/open', label: 'Exit Portal', category: 'Special', painter: paintExitOpen() },
  { id: 'flora/mushroom-red', label: 'Red Mushroom', category: 'Vegetation', painter: paintMushroomRed('standard/mushroom-red') },
  { id: 'flora/mushroom-blue', label: 'Blue Mushroom', category: 'Vegetation', painter: paintMushroomBlue('standard/mushroom-blue') },
  { id: 'flora/tree-pine', label: 'Pine Tree', category: 'Vegetation', painter: paintTreePine('standard/tree-pine') },
  { id: 'flora/tree-oak', label: 'Oak Tree', category: 'Vegetation', painter: paintTreeOak('standard/tree-oak') },
  { id: 'flora/tree-palm', label: 'Palm Tree', category: 'Vegetation', painter: paintTreePalm('standard/tree-palm') },
  { id: 'structure/ladder-wood', label: 'Wooden Ladder', category: 'Structures', painter: paintLadderWood() },
  { id: 'prop/chest-closed', label: 'Treasure Chest', category: 'Props', painter: paintChestClosed('standard/chest-closed') },
  { id: 'prop/chest-open', label: 'Open Chest', category: 'Props', painter: paintChestOpen('standard/chest-open') },
  { id: 'prop/barrel', label: 'Barrel', category: 'Props', painter: paintBarrel('standard/barrel') },
  { id: 'prop/crate', label: 'Storage Crate', category: 'Props', painter: paintCrate('standard/crate') },
  { id: 'prop/signpost', label: 'Signpost', category: 'Props', painter: paintSignpost('standard/signpost') },
];

export function registerStandardTiles(factory) {
  for (const definition of standardTileDefinitions) {
    factory.define(definition.id, definition.painter);
  }
  return factory;
}
